---

- name: prepare the pve host for k3s installation
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
    - name: Prepare the pve host for k3s installation
      include_tasks: tasks/prepare-lxc-host.yaml
